#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
TS_DIR="${TS_DIR:-$(realpath "$DIR/../../tree-sitter-wasm")}"

parse() {
    local typ="wat"
    while (( "$#" )); do
        case "$1" in
            -t) typ="$2"
                [[ "$typ" != "wat" ]] && [[ "$typ" != "wast" ]] &&
                    echo "unrecognized type $typ" && exit 1
                shift;;
            -*) echo "unrecognized $1" && exit 1;;
            *) break;;
        esac
        shift || true
    done
    local f="${1?}"
    echo "[INFO] parsing $DIR/$f"
    cd "$TS_DIR/$typ" && npx tree-sitter parse "$DIR/../$f"
}

parse "$@"
